CREATE TYPE "SalaryType" AS ENUM ('RANGE', 'FIXED', 'NEGOTIABLE');

ALTER TABLE "jobs"
ADD COLUMN "salary_type" "SalaryType" NOT NULL DEFAULT 'NEGOTIABLE',
ADD COLUMN "salary_min" INTEGER,
ADD COLUMN "salary_max" INTEGER,
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'VND';
